### ISSUE TITLE
Edit Description and Website on the home page of this repo

### ISSUE THREAD

**Issue by luixxiul** [brave/muon#137]
for now it is `Build cross platform desktop apps with web technologies http://electron.atom.io`

**Comment by bsclifton** [comment]
Updated :smile: 
![screen shot 2017-01-01 at 9 28 14 pm](https://cloud.githubusercontent.com/assets/4733304/21584551/3e68ea2e-d069-11e6-832c-051b46e24cd9.png)

**Comment by luixxiul** [comment]
Lovely :-)
