### ISSUE TITLE
Extension content_scripts do not load if partition is set

### ISSUE THREAD

**Issue by stewartlord** [brave/muon#257]
* Electron version: 4.3.1
* Operating system: elementary OS 0.4.1 Loki

Extension content_scripts do not to load for `BrowserWindow`s with `partition` set via `webPreferences` or for `webview`s with a `partition` attribute.

To reproduce:
1. Create an extension with content_scripts and load/enable it
2. Instantiate a new `BrowserWindow` and load 'https://google.com`
3. Observe that content_scripts are loaded
4. Pass `webPreferences: {partition: 'test'}` to new `BrowserWindow`
3. Observe that the content_scripts are not loaded

**Comment by bridiver** [comment]
This needs some additional information. What is the extension manifest? Can you create a sample app?

**Comment by stewartlord** [comment]
Thankfully this was my mistake and not a bug. If you set a partition then it creates a new session. Extensions must be loaded and enabled independently for each session. For instance:
```
  process.on('extension-ready', (extension) => {
    console.log("EXTENSION-READY *************");
    sess.extensions.enable(extension.id);
  })

  process.on('extension-load-error', (error) => {
    console.log('ERROR***************')
    console.error(error)
  })

  sess.extensions.load(
    '/home/slord/Projects/muon-quick/extensions/shift',
    {},
    'component'
  );

**Comment by bridiver** [comment]
you can use `app.on('browser-context-created', (e, session) => {` to get notifications when new sessions are are created
