### ISSUE TITLE
CrProductDirName doesn't have effect 

### ISSUE THREAD

**Issue by darkdh** [brave/muon#368]
introduced by https://github.com/brave/muon/commit/be85e8eda01f3df84f75bb128fe2c26e56517395#diff-5d1dc1824328b9f5b351cfc5b0ff5fd7

CrProductDirName is required by
https://github.com/brave/electron-packager/commit/0dcbc2d5b56b058e8ee9a2ec1f43f96d94f4925e for mac package build user folder override

**Comment by bridiver** [comment]
merged into https://github.com/brave/muon/pull/376
