### ISSUE TITLE
C63: Problem in Mac not rendering pages

### ISSUE THREAD

**Issue by hferreiro** [brave/muon#386]
In some situations the pages are not rendered in Mac.
Steps to reproduce:
* Open brave browser which by default loads `about:newtab` and click on a link from there. The URL and tab decoration are modified but the contents of the tab are not visible (you can inspect the new page though).
* Open brave browser and use the address bar to navigate to different URLs.

The problem is not present when you open Brave with a tab in a common URL (like wikipedia.org) and you just browse following the different links in that page. If you use the address bar the problem appears again.

We've been debugging the issue and when the issue happens some of the code is executed properly (loading, parsing and rendering/layout), that's why the tab decoration can show the favicon and the title; however, the painting code is not triggered. Painting is called for the address bar (it shows the load time) and the tab decoration (favicon and page title) but not for the contents of the tab itself.

We don't know if the issue is related to the browser-laptop app and how it handles the tab and its contents, or if it's a Chromium bug due to some Mac specific issue.
The problem is not reproducible in Windows and Linux.

It'd be good to have information about how the tabs contents are managed by browser-laptop, or if a reduced test case could be created (like a mini browser with a simple address bar and the tab contents) to see if the issue is reproducible in that scenario too.

**Comment by svillar** [comment]
https://github.com/brave/muon/commit/47035a01d2734e9eb7c310b9d12f8bc7b7e84a90

**Comment by ltilve** [comment]
Fixed on the mentioned commit.
