### ISSUE TITLE
Replace the uses of TabStripModelImpl->order_controller()

### ISSUE THREAD

**Issue by svillar** [brave/muon#395]
TabStripModel was refactored upstream and it's now the base class of TabStripModelImpl and 
TabStripModelExperimental. This commit just adds a couple of static_cast to access the TabStripModelImpl API. Brave is using order_controller() call which should be avoided if possible because:
1- it does not belong to the new TabStripModel interface
2- it's exposed just for unit tests

We should evaluate whether or not to migrate to newer Chromium APIs

**Comment by hferreiro** [comment]
This change was reverted upstream https://crrev.com/c559bd5b8a58.
