### ISSUE TITLE
Crash when restarting on C64 after switching the language

### ISSUE THREAD

**Issue by ltilve** [brave/muon#410]
We are detecting some crashes happening on a certain basis while using the browser, that end crashing due to a `readonly_shm_.IsValid()` failed check. 
There is a way to reproduce in a deterministic way, consisting on going to `about:preferences`, switching the language, and answering `yes` to the browser restart. Then the crash happens.
```
[1:1:1220/110521.309459:FATAL:shared_memory_posix.cc(367)] Check failed: readonly_shm_.IsValid(). 
```
This issue seems to be happening only on Linux. We have detected that reverting the last patches on master refering to shared memory management, https://github.com/brave/muon/commit/aa475ee8a052633ef7c2704eb58176d79a5043f2 and https://github.com/brave/muon/commit/852b715d6d177a4e990801502ae0b93da5b30afd, the crash is not happening.

**Comment by hferreiro** [comment]
Fixed after rebasing the the lastest muon.
