### ISSUE TITLE
Loading chrome extensions into muon (not brave)

### ISSUE THREAD

**Issue by shadowcodex** [brave/muon#414]
* Electron version: Latest
* Operating system: Macos

I'm looking to load a custom chrome extension into electron/muon. On muon's readme it states that it adds support for chrome extensions. However all details I have found for loading chrome extensions are for the brave/browser-laptop repo. These don't talk about loading chrome extensions directly into muon.

What path should I take for this?

A couple of my thoughts.

1. Figure out how to load extension directly in muon
2. Load extension in brave, and start stripping out unneeded options like brave pay etc...

Looking for some guidance on this.

**Comment by samuelmaddock** [comment]
The extensions API is available on [Session](https://github.com/electron/electron/blob/master/docs/api/session.md) objects. It doesn't appear to be well documented, so using the brave/browser-laptop code is probably the best current reference. Here's a snippet of code where [Brave loads an extension on the default session object](https://github.com/brave/browser-laptop/blob/master/app/extensions.js#L485).

Here's a minimal example for loading an extension from the main process. The path used should be the directory containing the extension's manifest.json file.
```js
import { session } from 'electron';
session.defaultSession.extensions.load(`/absolute/extension/path`, {}, 'unpacked');
```

The [API's C++ code](https://github.com/brave/muon/blob/master/brave/browser/api/brave_api_extension.cc) can give some insight into what the arguments do.

Keep in mind that Chrome extensions rely on certain `chrome.*` APIs being available, which Muon only implements parts of.

**Comment by shadowcodex** [comment]
Based on conversations from discord here are some additional things sam said.

add a `.npmrc` file with:

```
runtime = electron
target_arch = x64
brave_electron_version = 4.5.31
chromedriver_version = 2.33
target = latest
disturl=https://brave-laptop-binaries.s3.amazonaws.com/atom-shell/dist/
build_from_source = true
```

Quick start here: https://github.com/brave/muon-quick

> You can also load extension resources like a dashboard or popup html using the `chrome-extension://${extension-id}/${resource-name}` protocol

**Comment by shadowcodex** [comment]
Closing this now as my question is answered. Will re-open or comment if I have issues that need further addressing. Thanks @samuelmaddock

**Comment by chetan-northout** [comment]
while load metamask it's working fine in dev, but after making build of electron it gives`Uncaught Exception:
TypeError: Cannot read property 'load' of undefined
    at /home/northout/Development/First_blood/firstbloodRepond-challenge/firstblood/release-builds/firstBlood-linux-x64/resources/app/extensions.js:21:38
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)`
