### ISSUE TITLE
Webview causes crashes when used with chrome://brave/ using muon version 4.5.22 or later

### ISSUE THREAD

**Issue by shadowcodex** [brave/muon#415]
* Electron version: 4.5.32
* Operating system: Ubuntu 16.04

Upon trying to run a browserWindow using `chrome://brave/ + localPath` to enable `<webview>` it crashes as the webview loads saying:

<img width="725" alt="screen shot 2017-12-29 at 10 30 29 pm" src="https://user-images.githubusercontent.com/1348053/34451312-ef80aa86-ece7-11e7-94ac-13919841dac8.png">

This is a fresh install of Ubuntu via ISO running on virtualbox. I tried https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel#1122977 to no success.

Ideas?

**Comment by shadowcodex** [comment]
tried firejail to no avail as well.

**Comment by shadowcodex** [comment]
It crashes in windows too as it tries to load a <webview> if I load the front end using `file://` instead of `chrome://brave/` it works as intended except webviews won't render because they aren't allowed in regular files.

**Comment by shadowcodex** [comment]
Ok app works perfectly in windows, macos, and linux as long as I use muon version 4.5.21... Need a brave team dev to look into that. Seems like a bug.

**Comment by shadowcodex** [comment]
Summation:

If using v4.5.22 or later on windows / linux, when loading a `<webview>` under `chrome://brave/` muon will crash.

**Comment by bridiver** [comment]
do you have some sample code? We use webviews in Brave in `chrome://brave/` urls and they are working with the current muon release

**Comment by shadowcodex** [comment]
https://github.com/shadowcodex/muon-quick

Even this does not work on a fresh ubuntu or windows machine.

**Comment by shadowcodex** [comment]
@bridiver any ideas yet?

**Comment by samuelmaddock** [comment]
I'm also seeing the same issue. I've uploaded a Windows crash dump, I didn't see anything useful from debug logs.

[5aff0e7c-c5f0-4fbf-a115-481658d7f386.zip](https://github.com/brave/muon/files/1637787/5aff0e7c-c5f0-4fbf-a115-481658d7f386.zip)

**Comment by samuelmaddock** [comment]
Discussed the issue with @bridiver on Slack. Seems like it's related to [OOPIF](https://www.chromium.org/developers/design-documents/oop-iframes) being enabled. It's supposed to be disabled as of 9b172277813bbe2ed1f3a1e316710feb7cd2e0e1 which was introduced in v4.5.22 (Chromium 63 upgrade).

I'm going to continue debugging this week and hopefully we can find a fix.

**Comment by samuelmaddock** [comment]
@bridiver @shadowcodex Okay, the cause of the crash is a race condition when disabling the `GuestViewCrossProcessFrames` feature flag in [atom_browser_main_parts.cc](https://github.com/brave/muon/blob/master/atom/browser/atom_browser_main_parts.cc#L377-L381). If a `BrowserWindow` is constructed before this code is run, it doesn't get applied to any child guest views.

To demonstrate with the [muon-quick main.js code](https://github.com/brave/muon-quick/blob/c9c5b762a12a6c7e535c1e022b38658f38297202/main.js#L43), change the ready event handler to
```js
app.on('ready', () => {
  // BUG: Race condition causes GuestViewCrossProcessFrames feature flag to remain enabled
  // createWindow()

  // FIX: Wait until next frame for feature flag to get disabled
  setTimeout(createWindow, 0)
})
```
The hack above can be used as a temporary workaround until the native code is fixed.

**Comment by shadowcodex** [comment]
@samuelmaddock great find, I have tested on windows and this does solve the issue.
