### ISSUE TITLE
Weird stuff going on

### ISSUE THREAD

**Issue by kewde** [brave/muon#440]
Short version: I was working with muon and suddenly it also broke all other electron applications I have.
```
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ ls
electron  index.js  node_modules  package.json  package-lock.json  README.md
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ rm -rf node_modules/
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ cat package.json | grep "electron"
    "electron": "^1.7.10"
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ cat package.json | grep "brave"
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ cat package-lock.json | grep "brave"
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ npm install

> electron@1.7.10 postinstall /home/user/projects/electron/electron-sandbox/sandbox-preload-extended/node_modules/electron
> node install.js

npm WARN sandbox-preload-extended@1.0.0 No repository field.

added 152 packages in 7.355s
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ node index.js > /dev/null 2>&1 &
[1] 1704
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ ps aux | grep "electron"
user      1710  7.6  5.4 1138592 91248 pts/5   Sl   13:12   0:00 /home/user/projects/electron/electron-sandbox/sandbox-preload-extended/node_modules/electron/dist/electron --enable-sandbox ./electron/main.js
user      1713  0.5  1.7 323788 29744 pts/5    S    13:12   0:00 /home/user/projects/electron/electron sandbox/sandbox-preload-extended/node_modules/electron/dist/electron --type=zygote
user      1715  0.0  0.5 323788  8492 pts/5    S    13:12   0:00 /home/user/projects/electron/electron sandbox/sandbox-preload-extended/node_modules/electron/dist/electron --type=zygote
user      1747  1.8  3.9 701392 66264 pts/5    Sl   13:12   0:00 /home/user/projects/electron/electron sandbox/sandbox-preload-extended/node_modules/electron/dist/electron --type=zygote
user      1758  0.0  0.1  12728  2060 pts/5    S+   13:12   0:00 grep electron
```

I explicitly installed electron for this repo, yet it started behaving a lot like muon.

The odd thing is, the version test I made (-v flag) indicates that it's using the typical electron.
```
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ node versiontest.js
path to electron: /home/user/projects/electron/electron-sandbox/sandbox-preload-extended/node_modules/electron/dist/electron
[electron] v1.7.10

[electron] about to exit with code: 0
About to exit with code: 0
``` 

However, the output of using my **global** electron with the same version v1.7.10, it does create sandboxed renderer processes. 

```
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ electron -v
v1.7.10
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ electron --enable-sandbox ./electron/main.js > /dev/null 2>&1 &
[2] 2319
user@host:~/projects/electron/electron-sandbox/sandbox-preload-extended$ ps aux | grep "electron"
user      2319  0.4  1.4 611760 23456 pts/5    Sl   13:32   0:00 node /home/user/.nvm/versions/node/v6.11.5/bin/electron --enable-sandbox ./electron/main.js
user      2325  2.3  5.3 1138592 89904 pts/5   Sl   13:32   0:00 /home/user/.nvm/versions/node/v6.11.5/lib/node_modules/electron/dist/electron --enable-sandbox ./electron/main.js
user      2328  0.0  1.7 323784 29256 pts/5    S    13:32   0:00 /home/user/.nvm/versions/node/v6.11.5/lib/node_modules/electron/dist/electron --type=zygote
user      2330  0.0  0.5 323784  8516 pts/5    S    13:32   0:00 /home/user/.nvm/versions/node/v6.11.5/lib/node_modules/electron/dist/electron --type=zygote
user      2363  0.4  3.9 701388 65268 pts/5    Sl   13:32   0:00 /home/user/.nvm/versions/node/v6.11.5/lib/node_modules/electron/dist/electron --type=renderer --primordial-pipe-token=679BC735ADBB914B755F558E4DED4DE6 --lang=en-US --enable-sandbox --app-path=/home/user/.nvm/versions/node/v6.11.5/lib/node_modules/electron/dist/resources/default_app.asar --node-integration=false --webview-tag=false --enable-sandbox --preload=/home/user/projects/electron/electron-sandbox/sandbox-preload-extended/electron/renderer/preload-extended.js --context-isolation --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --service-request-channel-token=679BC735ADBB914B755F558E4DED4DE6 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101
user      2378  0.0  0.1  12732  2192 pts/5    S+   13:32   0:00 grep electron
```

**Comment by kewde** [comment]
More weird stuff, node version for brave?
```
user@host:~/projects/electron/electron-sandbox/muon-preload-extended/node_modules/electron-prebuilt/dist$ ./brave -v
vundefined
```

**Comment by bridiver** [comment]
muon won't take over anything and there is no `electron-sandbox` for muon. All renderer processes are sandboxed. If you have electron/muon installed globally and in project node_modules directories you probably have a path issue somewhere. I would not recommend installing muon globally

**Comment by kewde** [comment]
electron-sandbox is a project I'm working on, with multiple samples for sandboxing electron applications.

I figured out that somethings wrong, I'm not exactly sure how this occurred but yarn and npm are being inconsistent. muon-quick actually loaded the right brave version, and the chechsums indicate that there are different versions. I'll debug this further and hopefully figure out what's wrong.

```
user@host:~/projects/electron/electron-sandbox/muon-preload-extended$ cd node_modules/electron/dist/
user@host:~/projects/electron/electron-sandbox/muon-preload-extended/node_modules/electron/dist$ sha256sum brave 
89b48b67e676bec8ace3cd9ac69cab08cd22860a88c7a15bced8b5c5fb9fc47f  brave
user@host:~/projects/electron/electron-sandbox/muon-preload-extended/node_modules/electron/dist$ cd ../../../../../muon-quick/node_modules/electron/dist/
user@host:~/projects/electron/muon-quick/node_modules/electron/dist$ sha256sum brave 
51171a857b7d708856486cf62c4794405493385e1931714cadba7bc96a52f190  brave
```

**Comment by kewde** [comment]
The right brave version _does_ have sandboxed renderer process by the way :+1:

**Comment by kewde** [comment]
I've uninstalled my global electron version (never had a globally installed muon one), just to be sure but it's still happening.

Still applications that were previously running fine with electron (sandboxed) are now running horribly insecure :P I didn't make any changes, just installed muon in a completely different and unrelated directory. I know the muon electron-prebuilt fork uses some shared directories with electron when downloading things, so that's what made me suspicious.

**Comment by bridiver** [comment]
@kewde all brave renderer processes are sandboxed, but there is no electron-sandbox

**Comment by bridiver** [comment]
Steps to reproduce would help a lot. Thanks!

**Comment by kewde** [comment]
@bridiver 

I should probably explain myself a bit better, I'm currently working on a repository electron-sandbox-boilerplate.  https://github.com/kewde/electron-sandbox-boilerplate (previously known as electron-sandbox).

It aims to provide all the information one should need to create, run and package more secure sandboxed electron/muon applications. I'm also in the process of adding tutorials to _verify_ that the sandbox is actually working, I already got a seccomp-bpf check but there are many OS's to go through. The repository also contains (reasonably secure) code examples, initially for electron, but I'm adding muon now.

You guys seem like a helpful bunch, I'll do the effort of documenting everything and provide you with a repo to point clueless app developers to. Muon is wonderful but it's lacking a bit documentation, I hope to bridge that gap with my work on the boilerplate. 

Currently, electron does not provide a way to _package_ sandboxed applications, muon is the only baked-in solution for electron-builder. 

---
Anyways, back to the issue.

The issues I'm experiencing here are beyond odd, both the _normal_ electron binaries and the _malformed_ brave binaries aren't even spawning new renderer processes, only zygote processes.

I will do one last test round before passing this issue on to someone else, I will start with a fresh VM.
Run the normal electron examples I have (in electron-sandbox-boilerplate) and verify that they are indeed working. Then I will install muon and verify that the muon example is working as intended (currently isn't) and then I'll test the normal electron examples again. 

Let us hope it is just an anomaly on my system, but seeing it break in an unsandboxed way made me shiver a bit, hence the issue here.

**Comment by kewde** [comment]
Okay so a fresh VM has shed _some_ light on this issue.. 

The FREAKING FOLDER STRUCTURE kills sandboxes, on electron & brave.

This was the original structure:
```
index.js

electron/
    main.js
    renderer/
        index.html
        preload-extended.js
```

index.js would just

```
electron --enable-sandbox ./electron/main.js
```

and in main.js the the parameters in the BrowserWindow would point to the files in the renderer folder.

I moved everything up to the root directory and it's working.

```
index.js
main.js
index.html
preload-extended.js
```

**Comment by kewde** [comment]
Steps to reproduce:

```
git clone https://github.com/kewde/electron-sandbox-boilerplate.git
cd electron-sandbox-boilerplate/sandbox-preloader-extended/
yarn install #or npm install
```

Executing through a node app results in no sandbox:
```
node index.js 
```

Output:
```
path to electron: /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron
dirname: /home/user/electron-sandbox-boilerplate/sandbox-preload-extended
proc.spawn should execute: /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --enable-sandbox  /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/main.js
[electron] Main initialized
[electron] about to exit with code: 0
About to exit with code: 0
```
**Make note of the proc.spawn path, this is what it should execute & we'll execute this manually later on**

Now we hop onto another terminal to check the status of the electron executed by NodeJS.
```
ps aux | grep "electron"
```

output: 
```
user      6731  2.0 13.5 1130356 66424 pts/1   Sl+  20:49   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modul s/electron/dist/electron --enable-sandbox /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/main.js
user      6734  0.1  3.8 323780 18972 pts/1    S+   20:49   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/el ctron --type=zygote
user      6736  0.0  1.6 323780  8292 pts/1    S+   20:49   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/el ctron --type=zygote
user      6766  0.5 12.8 693188 63220 pts/1    Sl+  20:49   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/el ctron --type=zygote
user      6778  0.0  0.4  12728  2164 pts/2    S+   20:49   0:00 grep electron
```

We see no renderer processes.
You can go CTRL + C that `node index.js`
Grab the supposedly executed path from the output tho.

Let's run that manually
```
$ /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --enable-sandbox  /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/main.js
```

Check if it produces renderer processes:
```
user@host:~$ ps aux | grep "electron"
user      6780 10.0 15.4 1138584 75708 pts/1   Sl+  20:50   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --enable-sandbox /home/user/electron-sandbox-boilerplate/sand ox-preload-extended/main.js
user      6783  0.5  4.3 323780 21616 pts/1    S+   20:50   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --type=zygote
user      6785  0.0  1.6 323780  8228 pts/1    S+   20:50   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --type=zygote
user      6816  3.6 12.8 693188 62932 pts/1    Sl+  20:50   0:00 /home/user/electron-sandbox-boilerplate/sandbox-preload-extended/node_modules/electron/dist/electron --type=renderer --primordial-pipe-token=C10F2FBF05461689DB37D2CCEBEF7541 --lang=
user      6826  0.0  0.4  12728  2104 pts/2    S+   20:50   0:00 grep electron
```

Renderer processes appear O_o.


Same thing happen will happen for Brave I believe. Will test.

**Comment by kewde** [comment]
The fuck.

```
npm start
```
works **PERFECTLY** fine.
I am so done with NodeJS.

o_O

**Comment by kewde** [comment]
To recapitulate:
There are two issues here: one with folder structures and one with execution.

npm start worked fine with all the files in the root directory.
But it did not work fine with the original folder structure.

**Comment by kewde** [comment]
This gets weirder.
```
brave-v1.4.31-linux-x64.zip
```
Is the one I've been running, that's very very very old.

**Comment by kewde** [comment]
Cheers to https://github.com/brave/muon-quick/pull/5

Now running the latest brave.
Also .npmrc was missing which potentially explains why the "npm start" wasn't working.
Also the folder structure issue is also fixed for some odd reason.
