### ISSUE TITLE
Crash when navigating iframe in chrome://brave/ view

### ISSUE THREAD

**Issue by samuelmaddock** [brave/muon#451]
* Muon version: v4.5.21, v4.7.2
* Operating system: Windows 10 Build 16299

Setting the `src` attribute of an iframe within the document causes a crash when the parent frame uses the `chrome://brave` webui protocol.

To reproduce, fork muon-quick and add the following to the end of renderer.js
```js
const iframe = document.createElement('iframe')
iframe.src = 'data:text/html,test'
document.documentElement.appendChild(iframe)
```

It seems to crash [at the `CHECK` macro here](https://chromium.googlesource.com/chromium/src/+/532b7d7a9d9989f6da096bca91f5156045ac6f63/content/browser/frame_host/navigator_impl.cc#155)  due to `is_allowed_in_web_ui_renderer` being `false`.

**Comment by bridiver** [comment]
This is expected and correct behavior. The URLs for webui are intentionally limited for security reasons
