### ISSUE TITLE
C65: Tearing tabs off into a new window is flaky

### ISSUE THREAD

**Issue by ltilve** [brave/muon#478]
After updating C65 to 65.0.3322.3, tearing off to a new window one of the existing tabs might not result on a proper loading of the teared tab view at the new window. 

On the following code in `content/browser/renderer_host/render_widget_host_impl.cc`

```
  if (local_surface_id == last_local_surface_id_ &&
      new_surface_properties != last_surface_properties_) {
    static auto* crash_key = base::debug::AllocateCrashKeyString(
        "surface-invariants-violation", base::debug::CrashKeySize::Size256);
    base::debug::ScopedCrashKeyString key_value(
        crash_key,
        new_surface_properties.ToDiffString(last_surface_properties_));
    bad_message::ReceivedBadMessage(
        GetProcess(), bad_message::RWH_SURFACE_INVARIANTS_VIOLATION);
    return;
  }
```
in the void `RenderWidgetHostImpl::SubmitCompositorFrame()` call, as a consequence of some invariant invariant required by that code not being properly fullfiled on Brave.

**Comment by bridiver** [comment]
what is the crash key value?

**Comment by ltilve** [comment]
It's not a crash but a problem on the compositing; we have attached gdb to the process and is still there.
The page contents on the teared tab can be inspected, but still, reloading the tab is not rendering it.

**Comment by bridiver** [comment]
closed with https://github.com/brave/muon/commit/2231f5b7716e6bfeffa6ed06d5b2d6f0fe4c9a26
