### ISSUE TITLE
Disable user tracking via Crooked Style Sheets

### ISSUE THREAD

**Issue by jumde** [brave/muon#500]
https://github.com/jbtronics/CrookedStyleSheets

**Comment by flamsmark** [comment]
I assume this is a better repo than https://github.com/brave/browser-laptop/issues/12735 ?

**Comment by flamsmark** [comment]
Also related: https://www.mike-gualtieri.com/posts/stealing-data-with-css-attack-and-defense

**Comment by tomlowenthal** [comment]
This issue now lives at brave/brave-browser#818 .
