### ISSUE TITLE
Configure tor subprocess to listen on custom port

### ISSUE THREAD

**Issue by riastradh-brave** [brave/muon#530]
To avoid conflicting with default tor configuration and with the Tor Browser, we should run the tor subprocess (of https://github.com/brave/muon/pull/473) with a custom socks port number that is not likely to conflict.  The tor daemon uses 9050 by default, and the Tor Browser uses 9150 by default, so maybe we should use 9250.  Ideally, we could use a different number for release/beta/dev builds so that developers can run (say) brave-beta with Tor support at the same time as developing it.

This is a short-term stop-gap until we have a nice way to set the socks proxy address only after the tor daemon has launched (which we will want for https://github.com/brave/browser-laptop/issues/12936 unless we implement https://github.com/brave/muon/issues/469 first), and to cause Tor tabs to give meaningful feedback to users when tor is still launching rather than either failing cryptically or falling back to no proxy.

**Comment by bridiver** [comment]
in browser-laptop you could write different tor rc files by env using webpack

**Comment by riastradh-brave** [comment]
Rather than futz with a torrc file, we can just pass all the options by command-line arguments to the tor process, as in https://github.com/riastradh-brave/muon/tree/riastradh-tor-port (or, commit https://github.com/riastradh-brave/muon/commit/3d6408410623565d54a335666d4360718956845c).

**Comment by riastradh-brave** [comment]
This is being done in https://github.com/brave/muon/pull/473 now.
