### ISSUE TITLE
Decide what to do with tor daemon process when browser exits

### ISSUE THREAD

**Issue by riastradh-brave** [brave/muon#549]
Currently in the tor_browser_context branch, muon forks a tor daemon process in the background and lets it run forever.  With the default torrc file on, e.g., Ubuntu, it _happens_ to be the case that this operation is idempotent: the first instance will listen on port 9050, and subsequent processes will fail to bind to 9050 and die.  This is fragile, however, and we should be more intentional about what we rely on.

In particular, if the tor daemon process fails, we should provide diagnostics about why, including log output -- it is only a happy coincidence that this particular mode of failure works out for us, and if we ever let the OS decide on the socks port as in https://github.com/brave/browser-laptop/issues/12936 then we'll start littering the system with useless extra tor daemon processes.

Options:

1. Start a fresh tor daemon for every browser instance.  Try to find a way to reliably terminate the tor daemon process when the browser exits.
    - On Linux, it seems we can use the `kill_on_parent_death` launch option, but it doesn't look like this will work on anything other than Linux.
    - Maybe find a way to cause the tor daemon process to exit when, say, a control connection hangs up.
    - Maybe run an intermediate subprocess, brave -> janitor -> tor, to which brave talks via a socket, and when the socket is hung up the janitor kills the tor subprocess.
2. Decide on a way to reliably hook up to an ambient tor daemon process so that we can get diagnostics (log output, _etc._) with an idempotent launch operation.  This will have the effect that even after brave has exited, there may be a brave-initiated tor process running on user machines indefinitely, which strikes me as a little rude.

**Comment by riastradh-brave** [comment]
@darkdh is replacing the use of LaunchProcess, which is apparently not allowed in the thread we're using it in, by a service utility process, which should address this.  Additionally, it seems that even without `kill_on_parent_death`, the brave process on exiting will send SIGINT to the child on Linux at least, so perhaps this issue is moot after all.

**Comment by darkdh** [comment]
yeah https://github.com/brave/muon/pull/473/files#diff-df5c427fd693f9ebb2e5952cf0e9c8c7R248 guarantees that

**Comment by riastradh-brave** [comment]
We don't need to keep an ambient tor process running.  We should clean up after ourselves as
