### ISSUE TITLE
C66: Crash on tab detaching on Mac/Linux

### ISSUE THREAD

**Issue by ltilve** [brave/muon#571]
On `C66` detaching a tab to a separate window is causing both the windows to crash. It can be reproduced on Linux and Mac, while on Windows detaching tabs works as expected, but trying to reattach them into the original window has no effect.

**Comment by hferreiro** [comment]
Fixed by https://github.com/brave/muon/commit/8dfaa2c2cf11ffee73b371dd54e8c50697b4d051
