### ISSUE TITLE
Alert, prompt doesnt open.

### ISSUE THREAD

**Issue by davismiculis** [brave/muon#583]
* Electron version: **brave/muon v5.2.7, v6.0.5**
* Operating system: **Windows 10 x64**

Simply calling `alert('..')` or `prompt` methods doesnt open any dialogs and app kinda freezes.

To reproduce, download  basic app - [basic.zip](https://github.com/brave/muon/files/1959868/basic.zip) and then `npm install && npm run start` and write `alert('123');` in dev tools console.

**Comment by bsclifton** [comment]
@davismiculis in order for alert, prompt, or confirm to work, you'd need to implement them

For an example, you can check out this code in Brave:
https://github.com/brave/browser-laptop/blob/4e6cd0055a81894d803ba86b5535627b1ac12c3e/app/browser/tabMessageBox.js#L18-L27

**Comment by davismiculis** [comment]
Thanks, I'm using now:
```js
var dialog = require('electron').dialog
process.on('window-alert', function (webContents, extraData, title, message, defaultPromptText, shouldDisplaySuppressCheckbox, isBeforeUnloadDialog, isReload, muonCb) {
    dialog.showMessageBox(mainWindow, {
        type: 'warning',
        buttons: ['Ok'],
        detail: message
    }, function (buttonIndex) {
        muonCb(true, '', false)
    })
})
