### ISSUE TITLE
User Tor toggle restarts Tor process

### ISSUE THREAD

**Issue by flamsmark** [brave/muon#591]
If a user with Tor enabled for private tabs opens their browser when their Internet connection isn't available (or experiences any other transient problem), Brave will try to start Tor, timeout or fail, conclude that Tor is currently broken, and turn Tor off. In this case, a user might turn the Tor toggle back on, hoping to retry. If they do, we should restart the Tor process, acting as if it were just started.

To support this, Muon needs a command which allows the browser to restart the Tor process.

**Comment by riastradh-brave** [comment]
We now have logic in muon to implement this: https://github.com/brave/muon/pull/473/commits/c1d9af2b50380dc17bcb9d4ce30047118b2bdfb7

**Comment by riastradh-brave** [comment]
This is done for the connection error modal.  Remaining part for an always-available button to restart the tor daemon: https://github.com/brave/browser-laptop/issues/14578
