### ISSUE TITLE
C67: spellcheck not working on Linux/Win

### ISSUE THREAD

**Issue by ltilve** [brave/muon#597]
On the current status of the C67 PR https://github.com/brave/muon/pull/596, spellcheck seems that is not working.

**Comment by ltilve** [comment]
The issue is happening on Linux. On Mac Spellcheck seems to be working correctly.

**Comment by ltilve** [comment]
It's also failing on Win. Seems that is just working fine with Mac `use_browser_spellchecker`

**Comment by ltilve** [comment]
It seems I can still reproduce it on a fresh build and on with the brave-beta `67.0.3396.48`. I'm not seeing the red underline on textareas, even though it is enabled.
![typo](https://user-images.githubusercontent.com/2891281/40735692-1cb2bc6c-643c-11e8-9776-00906a41b059.png)
![spell1](https://user-images.githubusercontent.com/2891281/40735693-1cd02c16-643c-11e8-8572-34e084d30b04.png)

**Comment by darkdh** [comment]
this can only be reproducible on our `PACKAGED` build(npm run build-package), not from `blb` or `browser-laptop` launch (npm start)
@bsclifton ^^^

**Comment by darkdh** [comment]
fixed by https://github.com/brave/browser-laptop/commit/f3e97cdf3b49603325914a4dbcc92c754d8cc774
