### ISSUE TITLE
user prefs not applied to 'persist:tor' session

### ISSUE THREAD

**Issue by diracdeltas** [brave/muon#602]
the `persist:tor` session seems to inherit user prefs from `persist:default`; setting different prefs for this session does not work. for instance, `ses.userPrefs.setDictionaryPref('content_settings', ...)` for the `persist:tor` session in browser-laptop seems to do nothing.

if i change `appConfig.tor.partition` to `default` in this line, then it works as expected in private tabs (non-tor): https://github.com/brave/browser-laptop/commit/7fdf48470fca9383fe866587aeaddc22359c0706#diff-50b5521162e1f47690c976323e95e604R64

tested on 6.1.5

**Comment by riastradh-brave** [comment]
@jumde reports this is fixed.
